helm chart package and push to JFrog starter template
oneTakeda/.github pull request #17
Opened 2024-11-25 23:17 UTC by mpinedatkd

New Helm starter workflow template created

- https://takedaawsuseast.jfrog.io/ui/packages/helm:%2F%2Fhelm-workflow-starter -> package uploaded
- [https://github.com/oneTakeda/devops-starter-workflows-test/actions/runs/12020024628/job/33507797469 -> tested workflow ](https://github.com/oneTakeda/devops-starter-workflows-test/actions/runs/12040822079/workflow)

2024-11-26 14:02 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          curl -u${{ vars.JFROG_REPO_USER }}:${{ secrets.JFROG_REPO_TOKEN }} -T "CHART_NAME-package_version.tgz" "https://takedaawsuseast.jfrog.io/artifactory/JFROG_REPO_NAME-helm-local/CHART_NAME-pa
There's a discrepancy between this command and the one at https://mytakeda.sharepoint.com/sites/DevOps/SitePages/Container-deployment.aspx#building-and-pushing-your-docker-images-and-helm-charts-to-jfrog-within-github-actions
How would you suggest resolving it?

2024-11-26 14:05 UTC, jgleonard-takeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          curl -u${{ vars.JFROG_REPO_USER }}:${{ secrets.JFROG_REPO_TOKEN }} -T "CHART_NAME-package_version.tgz" "https://takedaawsuseast.jfrog.io/artifactory/JFROG_REPO_NAME-helm-local/CHART_NAME-pa
We should use native commands rather than curl.  There should also be an authentication step.

2024-11-26 14:06 UTC, jgleonard-takeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +        working-directory: ./path/to/helm/charts
This is unclear and I don't think it's a good idea.  It's not necessary when the path is used in the later step.

2024-11-26 14:08 UTC, jgleonard-takeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          version: ${{ vars.HELM_VERSION }}
This version variable isn't mentioned at the top of the file and it isn't defaulted or used here so this workflow won't work.

2024-11-26 14:12 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +        working-directory: ./path/to/helm/charts
Should probably be singular rather than plural, because I assume only one helm chart is packaged by this workflow, right? I.e. `charts` -> `chart`

Also, I suspect that defining defaults.run.working-directory may not be the best method for a starter workflow
Maybe just instead templating the `.` on line 43 with some variable that you ask the user to fill in.
That might lead to less side effects

2024-11-26 14:15 UTC, jgleonard-takeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +        working-directory: ./path/to/helm/charts
We shouldn't set a working-directory on a starter workflow as it could lead to unintended effects

2024-11-26 23:45 UTC, mpinedatkd commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +        working-directory: ./path/to/helm/charts
removed

2024-11-26 23:45 UTC, mpinedatkd commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          version: ${{ vars.HELM_VERSION }}
deleted

2024-11-26 23:45 UTC, mpinedatkd commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +        working-directory: ./path/to/helm/charts
fixed

2024-11-26 23:56 UTC, mpinedatkd commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          curl -u${{ vars.JFROG_REPO_USER }}:${{ secrets.JFROG_REPO_TOKEN }} -T "CHART_NAME-package_version.tgz" "https://takedaawsuseast.jfrog.io/artifactory/JFROG_REPO_NAME-helm-local/CHART_NAME-pa
I found that the only way to push to helm is using the jfrog cli and not helm cli, helm push works only for helm OCI artifacts, even though it let the login, I tried many times to push it but there's always an error, but when I tried the push on an OCI type, it worked! [OCI artifact](https://takedaawsuseast.jfrog.io/ui/repos/tree/General/mariotest).

2024-11-27 10:23 UTC, MarioUhrikTakeda requested changes
Sounds to me like we need to make a choice whether we're going to endorse Helm OCI vs "classic" Helm, or both.
I can't make an authoritative decision, but I'd intuitively go with Helm OCI since it's newer, and we could potentially add classic Helm later.

2024-11-27 10:23 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          helm package ./path/helm/folder --version '<package_version>'
The `./path/helm/folder` needs to be edited by the user, but it's not as obvious as it should be.
Consider at least using the same `'<TEXT>'` syntax as in the rest of the workflow

2024-11-27 10:23 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          jf rt u <CHART_NAME-package_version>.tgz <JFROG_ARTIFACT_DIR>/<path-to-upload-dir>/
I find it hard to believe that native Helm commands can't be used to build a Helm OCI chart and push to Helm OCI JFrog repo. Can you double-check?
https://jfrog.com/help/r/jfrog-artifactory-documentation/helm-oci-repositories

2024-11-27 10:26 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          curl -u${{ vars.JFROG_REPO_USER }}:${{ secrets.JFROG_REPO_TOKEN }} -T "CHART_NAME-package_version.tgz" "https://takedaawsuseast.jfrog.io/artifactory/JFROG_REPO_NAME-helm-local/CHART_NAME-pa
Continuing this conversation in my new review
https://github.com/oneTakeda/.github/pull/17#pullrequestreview-2464586725

2024-11-27 12:07 UTC, balaz-tomas commented
> Sounds to me like we need to make a choice whether we're going to endorse Helm OCI vs "classic" Helm, or both. I can't make an authoritative decision, but I'd intuitively go with Helm OCI since it's newer, and we could potentially add classic Helm later.
> 
> Please ensure that when this PR is merged, no discrepancies appear between

@MarioUhrikTakeda I'd like to bring another fact to consider, related to deployment of Helm Charts via Harness CD/GitOps

If we want to use pipeline triggers with helm charts (watch helm repo and trigger CD pipeline on creation of new chart version), we can't use _OCI Helm Registries_ with _Helm Chart Trigger_ on Harness
https://developer.harness.io/docs/platform/triggers/trigger-pipelines-on-new-helm-chart#oci-helm-registries-are-not-supported-with-harness-triggers

It's not confirmed we will go with neither of CD pipelines (without GitOps) and Helm Chart Triggers (maybe we can use [New Artifact trigger](https://developer.harness.io/docs/platform/triggers/trigger-on-a-new-artifact) if it isn't coupled strictly with docker images only), but I think we should test it how it works before we make a final decision

2024-11-27 12:39 UTC, MarioUhrikTakeda commented
Thanks @balaz-tomas
Perhaps both OCI and non-OCI helm starter workflows would make sense then

2024-11-27 14:16 UTC, mpinedatkd commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          jf rt u <CHART_NAME-package_version>.tgz <JFROG_ARTIFACT_DIR>/<path-to-upload-dir>/
There's a confusion, helm cli works for OCI Helm but not for regular ones. ([here](https://jfrog.com/help/r/jfrog-artifactory-documentation/deploy-helm-charts)). I tried many times to push one image using `helm push` to repos created by the automation (which are not OCI, including a new one)  and there's an error `invalid content digest in response: invalid checksum digest format` and that doesn't happen with OCI, worked fine.

2024-11-27 14:58 UTC, mpinedatkd commented
> Thanks @balaz-tomas Perhaps both OCI and non-OCI helm starter workflows would make sense then

Yeah I figured all of you are mentioning in this PR, maybe we should discuss having both or migrate the current to OCI type and there're not too much helm repos in JF

2024-11-27 15:58 UTC, MarioUhrikTakeda requested changes
A couple more improvements, but I think we're almost there

2024-11-27 15:58 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          jf c add --artifactory-url=https://takedaawsuseast.jfrog.io/artifactory --user='${{ vars.JFROG_REPO_USER }}' --password='${{ secrets.JFROG_REPO_TOKEN }}'
Here I'd suggest taking advantage of our Org Variable containing the JFrog URL instead of hardcoding it
I.e. ${{ vars.JFROG_URL }}/artifactory

2024-11-27 15:58 UTC, MarioUhrikTakeda commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          jf rt u <CHART_NAME-package_version>.tgz <JFROG_ARTIFACT_DIR>/<path-to-upload-dir>/
`<JFROG_ARTIFACT_DIR>` seems to be the Repo name - in that case, I think we should rename `<JFROG_ARTIFACT_DIR>` to something more clear, such as `<JFROG_REPO_NAME>`

Also, I'd suggest `<path-to-upload-dir>` to actually be `<CHART_NAME>`

2024-11-27 16:23 UTC, mpinedatkd commented on workflow-templates/jfrog-build-and-push-helm-charts.yml
> +          jf rt u <CHART_NAME-package_version>.tgz <JFROG_ARTIFACT_DIR>/<path-to-upload-dir>/
Also this need to be updated in the sharepoint, when the PR approved I'll be updating documentation

2024-11-27 18:35 UTC, MarioUhrikTakeda approved these changes

2024-11-27 18:55 UTC, MarioUhrikTakeda requested changes
Please add the https://github.com/jfrog/setup-jfrog-cli/blob/18e785fb220d332edbf01964f853ff0fcaa22220/README.md?plain=1#L134 suggestion

2024-11-27 23:57 UTC, mpinedatkd commented
> Please add the https://github.com/jfrog/setup-jfrog-cli/blob/18e785fb220d332edbf01964f853ff0fcaa22220/README.md?plain=1#L134 suggestion

Well I tried with many combinations trying to implement this solution:
- https://github.com/oneTakeda/devops-starter-workflows-test/actions/runs/12059613949/job/33628562470 -> here is ok the ping, but looks like it doesn't save the config
- https://github.com/oneTakeda/devops-starter-workflows-test/actions/runs/12059652709/workflow -> by implementing the env vars in the step it login but when the upload is tried it doesn't work.
- https://github.com/oneTakeda/devops-starter-workflows-test/actions/runs/12059869641/workflow -> here by trying to add the variables manually in the step it doesn't detect them  (by declaring them globally it worked, but it doesn't make sense to me use the have the same values picked by vars and secrets)

Please take a look on the tests
https://github.com/oneTakeda/devops-starter-workflows-test/actions/workflows/jfrog-build-and-push-helm-charts.yml

2024-11-28 09:30 UTC, MarioUhrikTakeda commented
@mpinedatkd 
Instead of this:
```
      - name: Setup JFrog CLI and login registry
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_USER: ${{ vars.STARTER_TEST_JFROG_USER }}
          JF_PASSWORD: ${{ secrets.STARTER_TEST_JFROG_TOKEN }}
      - run: |
          jf c add --artifactory-url=https://takedaawsuseast.jfrog.io/artifactory 
          jf rt ping
```
Try this:
```
      - name: Setup JFrog CLI and login registry
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.STARTER_TEST_JFROG_TOKEN }}
```
To save you time, I've tested it for you
https://github.com/oneTakeda/devops-starter-workflows-test/commit/7f786741b26f5ce395726914c408de73c8761df9
https://github.com/oneTakeda/devops-starter-workflows-test/actions/runs/12066039198

There was no need for any experimentation, because this is all clearly documented here: https://github.com/jfrog/setup-jfrog-cli?tab=readme-ov-file#authentication-methods
In one of your experiments, you came very close, but `JF_URL` is expected without the `/artifactory` path

2024-11-28 14:32 UTC, merged